#!/usr/bin/env ruby

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sum = 0
element_x1 = 1
element_x2 = 2

while element_x2 < 4_000_000
  sum += element_x2 if element_x2.even?
  element_tmp = element_x2
  element_x2 += element_x1
  element_x1 = element_tmp
end

puts sum
